config/routes.rb
Rails.application.routes.draw do
  resources :japanese_words
  resources :english_words
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/english_word.rb
class EnglishWord < ApplicationRecord
end

app/models/japanese_word.rb
class JapaneseWord < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/english_words_controller.rb
class EnglishWordsController < ApplicationController
  before_action :set_english_word, only: [:show, :edit, :update, :destroy]

  # GET /english_words
  # GET /english_words.json
  def index
    @english_words = EnglishWord.all
  end

  # GET /english_words/1
  # GET /english_words/1.json
  def show
  end

  # GET /english_words/new
  def new
    @english_word = EnglishWord.new
  end

  # GET /english_words/1/edit
  def edit
  end

  # POST /english_words
  # POST /english_words.json
  def create
    @english_word = EnglishWord.new(english_word_params)

    respond_to do |format|
      if @english_word.save
        format.html { redirect_to @english_word, notice: 'English word was successfully created.' }
        format.json { render :show, status: :created, location: @english_word }
      else
        format.html { render :new }
        format.json { render json: @english_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /english_words/1
  # PATCH/PUT /english_words/1.json
  def update
    respond_to do |format|
      if @english_word.update(english_word_params)
        format.html { redirect_to @english_word, notice: 'English word was successfully updated.' }
        format.json { render :show, status: :ok, location: @english_word }
      else
        format.html { render :edit }
        format.json { render json: @english_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /english_words/1
  # DELETE /english_words/1.json
  def destroy
    @english_word.destroy
    respond_to do |format|
      format.html { redirect_to english_words_url, notice: 'English word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_english_word
      @english_word = EnglishWord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def english_word_params
      params.require(:english_word).permit(:spell)
    end
end

app/controllers/japanese_words_controller.rb
class JapaneseWordsController < ApplicationController
  before_action :set_japanese_word, only: [:show, :edit, :update, :destroy]

  # GET /japanese_words
  # GET /japanese_words.json
  def index
    @japanese_words = JapaneseWord.all
  end

  # GET /japanese_words/1
  # GET /japanese_words/1.json
  def show
  end

  # GET /japanese_words/new
  def new
    @japanese_word = JapaneseWord.new
  end

  # GET /japanese_words/1/edit
  def edit
  end

  # POST /japanese_words
  # POST /japanese_words.json
  def create
    @japanese_word = JapaneseWord.new(japanese_word_params)

    respond_to do |format|
      if @japanese_word.save
        format.html { redirect_to @japanese_word, notice: 'Japanese word was successfully created.' }
        format.json { render :show, status: :created, location: @japanese_word }
      else
        format.html { render :new }
        format.json { render json: @japanese_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /japanese_words/1
  # PATCH/PUT /japanese_words/1.json
  def update
    respond_to do |format|
      if @japanese_word.update(japanese_word_params)
        format.html { redirect_to @japanese_word, notice: 'Japanese word was successfully updated.' }
        format.json { render :show, status: :ok, location: @japanese_word }
      else
        format.html { render :edit }
        format.json { render json: @japanese_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /japanese_words/1
  # DELETE /japanese_words/1.json
  def destroy
    @japanese_word.destroy
    respond_to do |format|
      format.html { redirect_to japanese_words_url, notice: 'Japanese word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_japanese_word
      @japanese_word = JapaneseWord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def japanese_word_params
      params.require(:japanese_word).permit(:spell)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/english_words_helper.rb
module EnglishWordsHelper
end

app/helpers/japanese_words_helper.rb
module JapaneseWordsHelper
end

app/views/english_words/_form.html.erb
<%= form_with(model: english_word, local: true) do |form| %>
  <% if english_word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(english_word.errors.count, "error") %> prohibited this english_word from being saved:</h2>

      <ul>
        <% english_word.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :spell %>
    <%= form.text_area :spell %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/english_words/edit.html.erb
<h1>Editing English Word</h1>

<%= render 'form', english_word: @english_word %>

<%= link_to 'Show', @english_word %> |
<%= link_to 'Back', english_words_path %>

app/views/english_words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>English Words</h1>

<table>
  <thead>
    <tr>
      <th>Spell</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @english_words.each do |english_word| %>
      <tr>
        <td><%= english_word.spell %></td>
        <td><%= link_to 'Show', english_word %></td>
        <td><%= link_to 'Edit', edit_english_word_path(english_word) %></td>
        <td><%= link_to 'Destroy', english_word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New English Word', new_english_word_path %>

app/views/english_words/new.html.erb
<h1>New English Word</h1>

<%= render 'form', english_word: @english_word %>

<%= link_to 'Back', english_words_path %>

app/views/english_words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Spell:</strong>
  <%= @english_word.spell %>
</p>

<%= link_to 'Edit', edit_english_word_path(@english_word) %> |
<%= link_to 'Back', english_words_path %>

app/views/japanese_words/_form.html.erb
<%= form_with(model: japanese_word, local: true) do |form| %>
  <% if japanese_word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(japanese_word.errors.count, "error") %> prohibited this japanese_word from being saved:</h2>

      <ul>
        <% japanese_word.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :spell %>
    <%= form.text_area :spell %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/japanese_words/edit.html.erb
<h1>Editing Japanese Word</h1>

<%= render 'form', japanese_word: @japanese_word %>

<%= link_to 'Show', @japanese_word %> |
<%= link_to 'Back', japanese_words_path %>

app/views/japanese_words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Japanese Words</h1>

<table>
  <thead>
    <tr>
      <th>Spell</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @japanese_words.each do |japanese_word| %>
      <tr>
        <td><%= japanese_word.spell %></td>
        <td><%= link_to 'Show', japanese_word %></td>
        <td><%= link_to 'Edit', edit_japanese_word_path(japanese_word) %></td>
        <td><%= link_to 'Destroy', japanese_word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Japanese Word', new_japanese_word_path %>

app/views/japanese_words/new.html.erb
<h1>New Japanese Word</h1>

<%= render 'form', japanese_word: @japanese_word %>

<%= link_to 'Back', japanese_words_path %>

app/views/japanese_words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Spell:</strong>
  <%= @japanese_word.spell %>
</p>

<%= link_to 'Edit', edit_japanese_word_path(@japanese_word) %> |
<%= link_to 'Back', japanese_words_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DynamicWordcard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>